import React, { useMemo } from "react";
import { UserProfile } from "../../types";
import { Award, CalendarDays, Flame, Scale, Timer } from "lucide-react";

interface ProgressReportProps { user: UserProfile; onLogWeight: (weight: number) => void; }
export const ProgressReport: React.FC<ProgressReportProps> = ({ user, onLogWeight }) => {
  const logs = user.workoutLogs || [];
  const minutes = logs.reduce((total, item) => total + item.minutes, 0);
  const calories = logs.reduce((total, item) => total + item.caloriesBurned, 0);
  const history = user.weightLogs?.length ? user.weightLogs : [{ date: user.joinedDate, weightKg: user.weightKg }];
  const heaviest = Math.max(...history.map((item) => item.weightKg));
  const lightest = Math.min(...history.map((item) => item.weightKg));
  const week = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - 6 + index); return { label: date.toLocaleDateString(undefined, { weekday: "narrow" }), number: date.getDate(), current: index === 6 }; }), []);
  return <div className="min-h-screen bg-[#f7f8fb] pb-28 text-[#171a22]"><div className="mx-auto max-w-3xl px-4 pt-6 sm:px-6 sm:pt-8"><header><p className="text-xs font-bold tracking-[0.16em] text-[#1769e0] uppercase">Keep going</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">PROGRESS</h1></header>
    <section className="mt-6 grid grid-cols-3 gap-3 rounded-3xl bg-white p-5 text-center shadow-[0_10px_30px_rgba(24,39,75,0.05)]">{[[Award, logs.length, "Workouts", "text-[#1769e0]"], [Flame, calories, "Kcal", "text-[#f0525c]"], [Timer, minutes, "Minutes", "text-[#7651d8]"]].map(([Icon, value, label, color]) => { const IconComponent = Icon as typeof Award; return <div key={label as string}><IconComponent className={`mx-auto h-6 w-6 ${color}`} /><p className="mt-2 text-2xl font-black">{value as number}</p><p className="text-xs font-medium text-[#7c838f]">{label as string}</p></div>; })}</section>
    <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-extrabold">History</h2><span className="text-sm font-bold text-[#1769e0]">All records</span></div><div className="rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><div className="grid grid-cols-7 gap-1 text-center">{week.map((day) => <div key={day.number} className="space-y-2"><span className="block text-xs text-[#8a909b]">{day.label}</span><span className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${day.current ? "bg-[#1769e0] text-white" : "text-[#686f7b]"}`}>{day.current ? "✓" : day.number}</span></div>)}</div><div className="mt-5 grid grid-cols-2 border-t border-[#eef0f4] pt-5"><div><p className="text-sm text-[#7c838f]">Day streak</p><p className="mt-1 flex items-center gap-1 text-lg font-black"><Flame className="h-5 w-5 fill-[#f0525c] text-[#f0525c]" /> {user.streakDays || 1}</p></div><div className="text-right"><p className="text-sm text-[#7c838f]">Personal best</p><p className="mt-1 text-lg font-black">{Math.max(1, user.streakDays || 1)} days</p></div></div></div></section>
    <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-extrabold">Weight</h2><button onClick={() => { const value = window.prompt("Enter current weight in kg", String(user.weightKg)); if (value && !Number.isNaN(Number(value))) onLogWeight(Number(value)); }} className="rounded-xl bg-[#1769e0] px-5 py-2.5 text-sm font-extrabold text-white">Log</button></div><div className="rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><div className="flex items-start justify-between"><div><p className="text-sm text-[#7c838f]">Current</p><p className="mt-1 text-3xl font-black">{user.weightKg} kg</p></div><div className="text-right text-sm"><p className="text-[#7c838f]">Heaviest <b className="ml-2 text-[#171a22]">{heaviest} kg</b></p><p className="mt-1 text-[#7c838f]">Lightest <b className="ml-2 text-[#171a22]">{lightest} kg</b></p></div></div><div className="mt-7 h-24 rounded-2xl bg-[linear-gradient(180deg,rgba(23,105,224,0.1),transparent)]"><svg viewBox="0 0 320 90" className="h-full w-full" preserveAspectRatio="none"><path d="M0,58 C55,50 80,68 130,45 S215,54 260,31 S295,40 320,20" fill="none" stroke="#1769e0" strokeWidth="3" /></svg></div></div></section>
  </div></div>;
};
