import React from "react";
import { Apple, ArrowRight, Bot, CheckCircle2, Dumbbell, Play, Sparkles } from "lucide-react";

interface LandingPageProps { onStartOnboarding: () => void; onExploreWorkouts: () => void; }

export const LandingPage: React.FC<LandingPageProps> = ({ onStartOnboarding, onExploreWorkouts }) => (
  <div className="relative min-h-screen overflow-hidden bg-[#f7f8fb] pb-12 text-[#171a22]">
    <div className="mx-auto max-w-3xl px-4 pt-10 sm:px-6 sm:pt-16">
      <section className="relative overflow-hidden rounded-[32px] bg-gradient-to-br from-[#1d75ed] via-[#1769e0] to-[#0b4ebd] px-6 py-9 text-white shadow-xl shadow-blue-200 sm:px-10">
        <div className="absolute -right-12 -top-14 h-60 w-60 rounded-full border-[28px] border-white/10" />
        <div className="relative max-w-lg"><span className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-bold"><Sparkles className="h-4 w-4" /> PERSONALIZED HOME FITNESS</span><h1 className="mt-5 text-4xl font-black leading-tight sm:text-5xl">MOVE BETTER.<br />FEEL STRONGER.</h1><p className="mt-4 text-sm leading-6 text-blue-100 sm:text-base">Short, equipment-free workouts, helpful coaching and nutritious food suggestions designed around you.</p><button onClick={onStartOnboarding} className="mt-7 flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-extrabold text-[#1769e0]">Build my plan <ArrowRight className="h-4 w-4" /></button></div>
      </section>
      <section className="mt-7"><h2 className="text-xl font-black">Everything for your routine</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><article className="rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#eaf1ff] text-[#1769e0]"><Dumbbell className="h-5 w-5" /></span><h3 className="mt-4 font-extrabold">No-equipment training</h3><p className="mt-1 text-sm leading-5 text-[#737987]">Build strength in your own space.</p></article><article className="rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#ebf8ef] text-[#32a852]"><Apple className="h-5 w-5" /></span><h3 className="mt-4 font-extrabold">Smart food ideas</h3><p className="mt-1 text-sm leading-5 text-[#737987]">Meals tailored to your profile.</p></article><article className="rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#f1ecff] text-[#7651d8]"><Bot className="h-5 w-5" /></span><h3 className="mt-4 font-extrabold">AI coach</h3><p className="mt-1 text-sm leading-5 text-[#737987]">Guidance whenever you need it.</p></article></div></section>
      <section className="mt-7 rounded-3xl bg-white p-5 shadow-[0_10px_30px_rgba(24,39,75,0.05)]"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[#fff3d9] text-[#ef9a1b]"><CheckCircle2 className="h-5 w-5" /></span><p className="font-bold">Your plan adapts to your goal, experience, height and weight.</p></div><button onClick={onExploreWorkouts} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#1769e0] py-3.5 text-sm font-extrabold text-white"><Play className="h-4 w-4 fill-current" /> Explore my workouts</button></section>
    </div>
  </div>
);
